import ujson


class Secret:
    """Reads all secrets from secret.json on the device filesystem.

    secret.json is never committed to source control.  For the emulator it is
    generated by run-qemu.sh; for real hardware it is uploaded by
    `make upload-scripts` before flashing.
    """

    _cache = None

    @classmethod
    def _load(cls):
        if cls._cache is None:
            try:
                with open("secret.json") as f:
                    cls._cache = ujson.load(f)
            except (OSError, ValueError):
                cls._cache = {}
        return cls._cache

    @classmethod
    def get(cls, key, default=None):
        return cls._load().get(key, default)

    # ── Typed accessors ────────────────────────────────────────────────────────

    @classmethod
    def wifi_ssid(cls):
        return cls.get("wifi_ssid", "myssid")

    @classmethod
    def wifi_password(cls):
        return cls.get("wifi_password", "")

    @classmethod
    def mqtt_broker(cls):
        return cls.get("mqtt_broker", "192.168.1.100")

    @classmethod
    def mqtt_port(cls):
        return int(cls.get("mqtt_port", 1883))

    @classmethod
    def thing_name(cls):
        return cls.get("thing_name", "esp32p4-device-01")

    @classmethod
    def camera_proxy_url(cls):
        return cls.get("camera_proxy_url")

    @classmethod
    def is_emulator(cls):
        return bool(cls.get("emulator", False))
