import ujson


class Secret:
    """Reads all secrets from secret.json on the device filesystem.

    secret.json is never committed to source control.  For the emulator it is
    generated by run-qemu.sh; for real hardware it is uploaded by
    `make upload-scripts` before flashing.
    """

    _cache = None

    @classmethod
    def _load(cls):
        if cls._cache is None:
            try:
                with open("secret.json") as f:
                    cls._cache = ujson.load(f)
            except (OSError, ValueError):
                cls._cache = {}
        return cls._cache

    @classmethod
    def get(cls, key, default=None):
        return cls._load().get(key, default)

    # ── WiFi ───────────────────────────────────────────────────────────────────

    @classmethod
    def wifi_ssid(cls):
        return cls.get("wifi_ssid", "myssid")

    @classmethod
    def wifi_password(cls):
        return cls.get("wifi_password", "")

    # ── MQTT ───────────────────────────────────────────────────────────────────

    @classmethod
    def mqtt_broker(cls):
        """Broker address for real hardware (LAN IP or AWS endpoint)."""
        return cls.get("mqtt_broker", "192.168.1.100")

    @classmethod
    def mqtt_broker_emulator(cls):
        """Broker address when running in the Docker/QEMU emulator.
        Resolves to 10.0.2.2 (QEMU user-net host) which socat relays
        to the localstack container on the Docker bridge network.
        """
        return cls.get("mqtt_broker_emulator", "10.0.2.2")

    @classmethod
    def mqtt_port(cls):
        """Plain TCP port — used by the emulator only."""
        return int(cls.get("mqtt_port", 1883))

    @classmethod
    def mqtt_ssl_port(cls):
        """TLS port — used on real hardware (LocalStack and AWS)."""
        return int(cls.get("mqtt_ssl_port", 8883))

    @classmethod
    def thing_name(cls):
        return cls.get("thing_name", "esp32p4-device-01")

    # ── SSL / TLS ──────────────────────────────────────────────────────────────

    @classmethod
    def mqtt_ssl_verify(cls):
        """Verify server certificate.  False for LocalStack, True for real AWS."""
        return bool(cls.get("mqtt_ssl_verify", False))

    @classmethod
    def ca_cert(cls):
        """Path to CA certificate PEM file, or None to skip verification."""
        return cls.get("ca_cert")

    @classmethod
    def device_cert(cls):
        """Path to device certificate PEM file."""
        return cls.get("device_cert")

    @classmethod
    def device_key(cls):
        """Path to device private key PEM file."""
        return cls.get("device_key")

    # ── Runtime ────────────────────────────────────────────────────────────────

    @classmethod
    def camera_proxy_url(cls):
        return cls.get("camera_proxy_url")

    @classmethod
    def is_emulator(cls):
        return bool(cls.get("emulator", False))
